all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/takima/.ssh/id_rsa_ansible
    my_db_user: user
    my_db_password: pwd # should be encrypted with a vault
    my_db_name: db
    my_front_name: front
    my_db_hostname: database
    my_application_name: my-api
    my_docker_repo: maximepakulatakima
    my_server: http://mpakula.takima.cloud:8080
  children:
    prod:
      hosts: mpakula.takima.cloud