- name: Launch application
  docker_container:
    name: "{{ my_application_name }}"
    image: "{{ my_docker_repo }}/tp-devops-simple-api"
    pull: yes # When using latest
    recreate: yes
    networks:
      - name: "my_network"
    ports:
      - 8080:8080
    env:
      SPRING_DATASOURCE_USERNAME: "{{ my_db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ my_db_password }}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ my_db_hostname}}:5432/{{ my_db_name }}"